name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  issues: write

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Remove preview directory
        run: |
          PREVIEW_PATH="pr-${{ github.event.pull_request.number }}"

          # Ensure we have latest gh-pages to avoid push conflicts
          git fetch origin gh-pages
          git checkout gh-pages
          git pull --rebase origin gh-pages || true

          if [ -d "$PREVIEW_PATH" ]; then
            echo "Removing preview directory: $PREVIEW_PATH"
            git rm -rf "$PREVIEW_PATH" || true
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            if git diff --staged --quiet; then
              echo "Nothing to commit after removal (nothing staged)"
            else
              git commit -m "cleanup: remove preview for PR #${{ github.event.pull_request.number }}" || true
              git push origin gh-pages || true
              echo "Preview cleaned up successfully"
            fi
          else
            echo "Preview directory not found, may have been already cleaned up"
          fi

      - name: Comment cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'Preview cleaned up after PR closure.'
            });
